swagger2.title: 药品模块
swagger2.enable: true
server:
  port: 8081
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER
security:
  oauth2:
    client:
      client-id: drug
      client-secret: 123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user/me
      token-info-uri: http://localhost:8080/oauth/check_token
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///medicine?serverTimezone=UTC
    username: root
    password: aWVZQ40uOVqUvhyZp35KSzqV15wRmWB9j7MsjZA2UeHvUSMsmQzpVHTjPvIdf7BbDJ83E7ZSsStViSV3+ygRXg==
    druid:
      connect-properties:
        config.decrypt: true
        config.decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ/OwmiSTJQRlhpf09zzU+jOsEO+APTlx9OSmLUW2wxM+XeCfAHC96vrU9VApNKOQP6qz6TzGi5rMLkpOc/38b0CAwEAAQ==
      filter:
        config:
          enabled: true # 启动ConfigFilter
      initial-size: 5 # 连接池初始化大小
      min-idle: 10 # 最小空闲连接数
      max-active: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0