swagger2.title: 就诊模块
swagger2.enable: true
server:
  port: 8082
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER
security:
  oauth2:
    client:
      client-id: outpatient
      client-secret: 123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user/me
      token-info-uri: http://localhost:8080/oauth/check_token
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///outpatient_service?serverTimezone=UTC
    username: root
    password: aWVZQ40uOVqUvhyZp35KSzqV15wRmWB9j7MsjZA2UeHvUSMsmQzpVHTjPvIdf7BbDJ83E7ZSsStViSV3+ygRXg==
    druid:
      connect-properties:
        config.decrypt: true
        config.decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ/OwmiSTJQRlhpf09zzU+jOsEO+APTlx9OSmLUW2wxM+XeCfAHC96vrU9VApNKOQP6qz6TzGi5rMLkpOc/38b0CAwEAAQ==
      filter:
        config:
          enabled: true # 启动ConfigFilter
      initial-size: 5 # 连接池初始化大小
      min-idle: 10 # 最小空闲连接数
      max-active: 20